#!/bin/bash

echo "Clone all Github repos of a specific user."

read -p "Do the repos come from a user or an Organization? (user / orgs) " TYPE
read -p "Enter the Github username: " USERNAME

CNTX={TYPE}; NAME={USERNAME}; PAGE=1
curl "https://api.github.com/$CNTX/$NAME/repos?page=$PAGE&per_page=100" |
  grep -e 'clone_url*' |
  cut -d \" -f 4 |
  xargs -L1 git clone
